### ISSUE TITLE
Code problems

### ISSUE THREAD

**Issue by stekicar** [karioja/vedirect#3]
Hi,
def read_data(self):
    while True:
    byte = self.ser.read(1)
    packet = self.input(byte)

does not return any value. Is this correct?

Running: python3 vedirect.py --port /dev/ttyS0 does not produce any response.
Using regular serial read code returns values.

I am trying to run a code:
import vedirect
smartsolar = vedirect.vedirect('/dev/ttyS0', 15)
paket = smartsolar.read_data_single()
print(paket)

but it keeps hanging at: paket = smartsolar.read_data_single()

Am I doing something wrong?

**Comment by mano8** [comment]
Hi, python 3 is not supported i think...

**Comment by stekicar** [comment]
Hi. Thank you for reply. I have changed the code for python3. This is because python2 code did not work either.

**Comment by mano8** [comment]
Hi better in python 2 have some changes to do for python3.
Your serial port address is sure? In my case must be  '/dev/ttyUSB0' for bmv700...

**Comment by mano8** [comment]
if no valid data retrieved read_data_single() never stop. 
Think your serial port or driver can be the problem.
To ensure you can test with socat and vedirectsim
but you can add timeout to stop.
(packet blocks must be read every second. so you can put 2 sec timeout here)
`
import time

    def read_data_single(self):
        t_start = time.time()
        while True:
            byte = self.ser.read(1)
            packet = self.input(byte)
            if (packet != None):
                return packet
            if (time.time() - t_start) > 5:
                return None
`

**Comment by stekicar** [comment]
Thank you for reply. It works with python2 now. I had problem with my voltage divider, loose connection maybe.
Thank you!
